language: java
jdk: openjdk11

script:
  - ls -la
  - cd DUMESTRE-HUGDELARAUZE
  - sh cleanAll
  - sh genDeliverable
  - cd ../
  - mv DUMESTRE-HUGDELARAUZE.tar.gz Tools/
  - cd Tools/
  - sh Deploiement DUMESTRE-HUGDELARAUZE
 
