language: java
jdk: openjdk11

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ant
    - ant-optional

script:
  - ant runUnitTest
  - ant runDeploymentTest
 
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH}
  file: "artifacts/Bartoli-Dumestre-Francis-Gueye-Hugdelarauze.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
