language: java
jdk: openjdk11

script:
  - ls -la
  - cd DUMESTRE-HUGDELARAUZE
  - sh cleanAll
  - sh genDeliverable
  - cd ../
  - mv DUMESTRE-HUGDELARAUZE.tar.gz Tools/
  - cd Tools/
  - sh Deploiement DUMESTRE-HUGDELARAUZE
 
deploy:
  provider: releases
  api_key: ${Travis_CI-SIT213_Project}
  file: "DUMESTRE-HUGDELARAUZE.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true