language: java
jdk: openjdk11

script:
  - ant runTest
  - ant runDeploymentTest
 
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH}
  file: "Bartoli-Dumestre-Francis-Hugdelarauze.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true