language: java
jdk: openjdk11

script:
  - cd DUMESTRE-HUGDELARAUZE
  - ant genDeliverable
  - mv deliverable/DUMESTRE-HUGDELARAUZE.tar.gz ../Tools/
  - cd ../Tools/
  - sh Deploiement DUMESTRE-HUGDELARAUZE
 
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH}
  file: "DUMESTRE-HUGDELARAUZE.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true